version: '2'
services:
  proxy:
    build: ./
    networks:
      - web1
      - web2
    volumes:
      - .:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
#      - ./ssl:/etc/nginx/conf.d/
#      - ./ssl/web2.crt:/etc/nginx/conf.d/default.conf
#      - ./ssl/web1.key:/etc/nginx/conf.d/default.conf
#      - ./ssl/web2.key:/etc/nginx/conf.d/default.conf

    ports:
      - 80:80
      - 443:443

networks:
  web1:
    external:
      name: web1_default
  web2:
    external:
      name: web2_default






