version: "2"
services:
  redis: 
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379' 
  web:
    #build the python image from Dockerfile 
    build: .    
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
